# This workflow will create a changelog based on the Conventional Commits standard and bump the semver accordingly.
# See: https://www.npmjs.com/package/standard-version for documentation on the tool
name: Changelog/Version Management
on:
  push:
    branches: [ main ]
jobs:
  run-standard-version:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Config git
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Run Standard Version
      run: |
        npx standard-version
        git fetch origin $GITHUB_REF
        git push -f --follow-tags origin $GITHUB_REF
